name: "Release"

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  release-conda-store:
    name: 'PyPi Release conda-store-server'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - "conda-store"
          - "conda-store-server"
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install hatch
        run: |
          pip install hatch

      - name: Build Package
        run: |
          hatch build

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
